name: flutter_vm
description: A Flutter ViewModel implementation. Use Mixin for use in Statefull Widget or sample contructor for use in Stateless. This lib include UseCase.
version: 0.0.1+2
homepage: https://github.com/beppenmk/flutter_viewmodel

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  mockito: ^5.1.0

flutter:
